#!/usr/bin/env bash
# This is a bash script that configures localhost resolves to 127.0.0.2 and 
# facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.old

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
