#!/usr/bin/env bash
# Installing nginx on my server

apt-get update

apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo 'Hello World!' > index.html

cp index.html /var/www/html

systemctl start nginx

exit
