#!/usr/bin/env bash
# This is a bash script that pings an IP address passed as an argument

if [ "$1" == "" ]; then

	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 0
fi
ping "$1" -n 5
