#!/usr/bin/env bash
#This is a shell script that that displays to infinity and beyond indefinitely

sigt()
{
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
	exit 0
}

sigi()
{
	echo "Y U no love me?!"
}

sigq()
{
	rm -f /var/run/myscript.pid
	exit 0
}

trap 'sigt' SIGTERM
trap 'sigi' SIGINT
trap 'sigq' SIGQUIT

pid=$$

echo "$pid" > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 1
done
