#!/usr/bin/env bash
#This is a shell script that that displays to infinity and beyond indefinitely

sig()
{
	echo "I am invincible!!!"
	exit 0
}

i=1
while [ $i -eq 1 ]
do
	echo "To infinity and beyond"
	sleep 2
done


trap 'sig' SIGTERM

while true; do
	sleep 1
done
