#!/usr/bin/env bash
#This is a shell script that that displays to infinity and beyond indefinitely

sig()
{
	echo "I am invincible!!!"
}

trap 'sig' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
