#!/usr/bin/env bash
# This is a bash script that configures localhost resolves to 127.0.0.2 and 
# facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.old

sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i '$a\8.8.8.8 facebook.com' /etc/hosts
