#!/usr/bin/env bash
# This is a bash script that configures localhost resolves to 127.0.0.2 and 
# facebook.com resolves to 8.8.8.8

sudo sed -i 's/127.0.0.1/127.0.0.2g/' /etc/hosts

sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
